### PR TITLE
feat: add types for the configuration's default export

### PR DESCRIPTION
**Pull request by amirfarzamnia**
This PR adds types for the configuration's default export, simplifying development.

### CODE REVIEW

**Comment by amirfarzamnia** [comment]
> @amirfarzamnia can you please sign our cla?

Yeap, I did.

**Review by aladdin-add — CHANGES_REQUESTED** [review]
the testing is failing now - you can run `npm run test:snapshots:update` to update the snapshots.

**Comment by amirfarzamnia** [comment]
> the testing is failing now - you can run `npm run test:snapshots:update` to update the snapshots.

Done

**Review by aladdin-add — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
