### PR TITLE
chore: update readme

### PR DESCRIPTION
**Pull request by harish-sethuraman**
removed unwanted anchor. 

Can someone trigger tests for this PR? Tests fails for me in the main branch as well?

### CODE REVIEW

**Comment by harish-sethuraman** [comment]
Weird tests fail for `17.x` in this PR too 🤔

**Comment by aladdin-add** [comment]
has something changed in the experimental loader - it's used in our tests to mock esm?

**Comment by aladdin-add** [comment]
filed the issue in esmock: https://github.com/iambumblehead/esmock/issues/49

**Comment by harish-sethuraman** [comment]
Hey thanks. I was looking at the same. Should we consider any alternatives? or wait until it is fixed in esmock?

**Comment by aladdin-add** [comment]
it has been fixed in esmock. I've made a PR to upgrade: https://github.com/eslint/create-config/pull/26

**Comment by harish-sethuraman** [comment]
Closing as the tests runner are not failing in `17.8.0`

**Pull request closed without merging**
