### PR TITLE
feat: `eslint-plugin-react` supports ESLint v9

### PR DESCRIPTION
**Pull request by mdjermanovic**
`eslint-plugin-react` now supports ESLint v9.

This removes the prompt about whether to install ESLint v8.x, as well as compatibility utilities and `--force` flag when `eslint-plugin-react` is used.

### CODE REVIEW

**Review by aladdin-add — APPROVED** [review]
LGTM, thanks!

**Review by harish-sethuraman — APPROVED** [review]
LGTM. We might once want to re trigger the CI to pass.

**Comment by aladdin-add** [comment]
it's still blocked by https://github.com/actions/node-versions/pull/182.

**Comment by mdjermanovic** [comment]
All tests are green now.

**Pull request merged**
