### PR TITLE
ci: run tests in Node.js 21

### PR DESCRIPTION
**Pull request by fasttime**
This PR updates the GitHub Actions CI workflow to run tests also in Node.js 21.

### CODE REVIEW

**Comment by fasttime** [comment]
The build on Node.js 12.22.0 is now failing, probably because it's not supported by esmock:

https://github.com/iambumblehead/esmock/blob/v2.5.7/package.json#L60

I'll have to take a closer look later today.

**Comment by mdjermanovic** [comment]
I'll close-reopen to update the merge ref.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! I assume this was marked as draft to wait for https://github.com/eslint/create-config/pull/77, so I'm going to un-draft and merge.

**Comment by fasttime** [comment]
Thanks @mdjermanovic! Yes, I forgot to mark the PR as ready after the fix was merged.

**Pull request merged**
